---
Name: cookie-policy-notification
After: 'framework/*,cms/*'
---

PageController:
  extensions:
    - Novatio\CookiePolicy\CookiePolicy

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Novatio\CookiePolicy\SiteConfigCookiePolicy
